import type { NextPage } from "next";
import Head from "next/head";
import styles from "../../styles/Home.module.css";
import { track } from "@amplitude/analytics-browser";

const WithoutAmpli: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Without Ampli</h1>
        <button
          style={{ marginTop: "20px", fontSize: "20px" }}
          onClick={() => track("Add to Cart", { price: "123" })}
        >
          Track
        </button>
      </main>
    </div>
  );
};

export default WithoutAmpli;
