import type { NextPage } from "next";
import Head from "next/head";
import styles from "../../styles/Home.module.css";
import { ampli } from "../../src/ampli";

const WithAmpli: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>With Ampli</h1>
        <button
          style={{ marginTop: "20px", fontSize: "20px" }}
          onClick={() => {
            ampli.addToCart({
              price: 100,
              quantity: 1,
              product_category: "Cloth",
            });
          }}
        >
          Track
        </button>
      </main>
    </div>
  );
};

export default WithAmpli;
