import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import {
  identify,
  setGroup,
  groupIdentify,
  track,
  Identify,
} from "@amplitude/analytics-browser";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Ampli Cli/SDK Demo</h1>

        <button
          onClick={() =>
            track("Button Click", { name: "App", appVersion: "1.0.0" })
          }
          style={{ marginTop: "10rem", fontSize: "2rem" }}
        >
          Track
        </button>
      </main>
    </div>
  );
};

export default Home;
